apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-app-route
  namespace: demo-app
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress
  hostnames:
    - demo-app.opencloudhub.org
  rules:
    # Backend API routes
    - matches:
        - path:
            type: PathPrefix
            value: /api
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - group: ""
          kind: Service
          name: demo-app-genai-backend
          namespace: demo-app
          port: 8000
          weight: 1

    # Frontend (default/root path)
    # - matches:
    #     - path:
    #         type: PathPrefix
    #         value: /
    #   backendRefs:
    #     - group: ""
    #       kind: Service
    #       name: demo-app-frontend
    #       namespace: demo-app
    #       port: 80
