apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-db-user-es
  namespace: storage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: demo-app-db-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          app: demo-app-db-cluster
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: demo-app/storage/cnpg/demo-app
        property: username
    - secretKey: password
      remoteRef:
        key: demo-app/storage/cnpg/demo-app
        property: password