# Core service namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    opencloudhub.org/secret-registry: "true"
    opencloudhub.org/secret-gitops: "true"
  # ArgoCD should stay outside the mesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  # No ambient label - this is the control plane

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    istio.io/dataplane-mode: ambient

# Auth service namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    istio.io/dataplane-mode: ambient

# Observability service namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    istio.io/dataplane-mode: ambient
    opencloudhub.org/secret-minio: "true"
    opencloudhub.org/secret-grafana: "true"

# Storage service namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    istio.io/dataplane-mode: ambient
    opencloudhub.org/secret-pgadmin: "true"
    opencloudhub.org/secret-mlflow-db: "true"
    opencloudhub.org/secret-demo-app-db: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant
  labels:
    istio.io/dataplane-mode: ambient
    opencloudhub.org/secret-minio: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
  labels:
    istio.io/dataplane-mode: ambient

# MLOps namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops
  labels:
    istio.io/dataplane-mode: ambient
    opencloudhub.org/secret-registry: "true"
    opencloudhub.org/secret-gitops: "true"
    opencloudhub.org/secret-minio: "true"
    opencloudhub.org/secret-dvc: "true"
    opencloudhub.org/secret-mlflow-db: "true"
    opencloudhub.org/secret-demo-app-db: "true"
