---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    istio.io/dataplane-mode: ambient

---
# Not part of mesh for faster serving, no need for secure communication with other pods in cluster
apiVersion: v1
kind: Namespace
metadata:
  name: models
