apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-admin-es
  namespace: storage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: platform/storage/pgadmin/credentials
        property: password
