apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-credentials
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitops-repo
    creationPolicy: Owner
    # Add template with required ArgoCD repository secret format
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
  - secretKey: url
    remoteRef:
      key: platform/gitops/repos/gitops
      property: url
  - secretKey: type
    remoteRef:
      key: platform/gitops/repos/gitops
      property: type
  - secretKey: sshPrivateKey
    remoteRef:
      key: platform/gitops/repos/gitops
      property: sshPrivateKey