# =============================================================================
# Compute Configuration Templates
# =============================================================================
#
# Maps compute_type parameter to actual resource values.
# Keep this simple - just a lookup table.
#
# Usage:
#   templateRef:
#     name: compute-templates
#     template: map-compute-config
#   arguments:
#     parameters:
#       - name: compute_type
#         value: "gpu-small"
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: compute-templates
  namespace: mlops
  annotations:
    workflows.argoproj.io/description: "Map compute type to resource specifications"
spec:
  templates:
    - name: map-compute-config
      inputs:
        parameters:
          - name: compute_type
      outputs:
        parameters:
          - name: cpu_request
            valueFrom:
              path: /tmp/cpu_request.txt
          - name: cpu_limit
            valueFrom:
              path: /tmp/cpu_limit.txt
          - name: memory_request
            valueFrom:
              path: /tmp/memory_request.txt
          - name: memory_limit
            valueFrom:
              path: /tmp/memory_limit.txt
          - name: replicas
            valueFrom:
              path: /tmp/replicas.txt
          - name: gpu
            valueFrom:
              path: /tmp/gpu.txt
      script:
        image: alpine:latest
        command: [sh]
        source: |
          set -e

          COMPUTE_TYPE="{{inputs.parameters.compute_type}}"

          case "$COMPUTE_TYPE" in
            cpu-small)
              CPU_REQ="2"    ; CPU_LIM="3"
              MEM_REQ="4Gi"  ; MEM_LIM="5Gi"
              REPLICAS="1"   ; GPU="0"
              ;;
            cpu-small-distributed)
              CPU_REQ="2"    ; CPU_LIM="3"
              MEM_REQ="4Gi"  ; MEM_LIM="5Gi"
              REPLICAS="2"   ; GPU="0"
              ;;
            cpu-medium)
              CPU_REQ="4"    ; CPU_LIM="6"
              MEM_REQ="8Gi"  ; MEM_LIM="10Gi"
              REPLICAS="1"   ; GPU="0"
              ;;
            cpu-large)
              CPU_REQ="8"    ; CPU_LIM="12"
              MEM_REQ="16Gi" ; MEM_LIM="20Gi"
              REPLICAS="2"   ; GPU="0"
              ;;
            gpu-small)
              CPU_REQ="4"    ; CPU_LIM="6"
              MEM_REQ="16Gi" ; MEM_LIM="20Gi"
              REPLICAS="1"   ; GPU="1"
              ;;
            gpu-medium)
              CPU_REQ="8"    ; CPU_LIM="12"
              MEM_REQ="32Gi" ; MEM_LIM="40Gi"
              REPLICAS="1"   ; GPU="1"
              ;;
            gpu-large)
              CPU_REQ="16"   ; CPU_LIM="24"
              MEM_REQ="64Gi" ; MEM_LIM="80Gi"
              REPLICAS="1"   ; GPU="1"
              ;;
            *)
              echo "❌ Unknown compute type: $COMPUTE_TYPE"
              exit 1
              ;;
          esac

          echo -n "$CPU_REQ"  > /tmp/cpu_request.txt
          echo -n "$CPU_LIM"  > /tmp/cpu_limit.txt
          echo -n "$MEM_REQ"  > /tmp/memory_request.txt
          echo -n "$MEM_LIM"  > /tmp/memory_limit.txt
          echo -n "$REPLICAS" > /tmp/replicas.txt
          echo -n "$GPU"      > /tmp/gpu.txt

          echo ""
          echo "=========================================="
          echo "⚙️  COMPUTE CONFIGURATION"
          echo "=========================================="
          echo ""
          echo "  Type:      $COMPUTE_TYPE"
          echo ""
          echo "  CPU:       $CPU_REQ (request) / $CPU_LIM (limit)"
          echo "  Memory:    $MEM_REQ (request) / $MEM_LIM (limit)"
          echo "  GPU:       $GPU"
          echo "  Replicas:  $REPLICAS"
          echo ""
          echo "=========================================="
          echo "=========================================="
          echo ""
