# =============================================================================
# Shared Ray Job Templates
# =============================================================================
#
# Contract:
#   Platform provides:
#     - Tracking env vars (ARGO_WORKFLOW_UID, DOCKER_IMAGE_TAG, etc.)
#     - Platform config (MLFLOW_TRACKING_URI via ConfigMap)
#     - Model config (experiment/registry names via ConfigMap)
#     - Secrets (MinIO credentials)
#     - Compute resources (from compute-templates)
#
#   AI Team provides:
#     - Training image (code baked in)
#     - Entrypoint + training_args (hyperparameters, model config)
#
# Prerequisites:
#   - ConfigMap: mlops-platform-env
#   - ConfigMap: {model_name}-env
#   - Secret: minio-tenant-secret
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ray-templates
  namespace: mlops
spec:
  templates:
    - name: training-job
      inputs:
        parameters:
          # Job identity
          - name: job_prefix
          - name: image
          - name: entrypoint

          # Model config (references ConfigMap by name)
          - name: model_configmap

          # Compute (from compute-templates)
          - name: cpu
            default: "2"
          - name: memory
            default: "4Gi"
          - name: gpu
            default: "0"
          - name: replicas
            default: "1"

          # Data version (for traceability)
          - name: dvc_data_version

      outputs:
        parameters:
          - name: job_name
            valueFrom:
              jsonPath: "{.metadata.name}"

      resource:
        action: create
        successCondition: status.jobStatus == SUCCEEDED
        failureCondition: status.jobStatus in (FAILED, STOPPED)
        manifest: |
          apiVersion: ray.io/v1
          kind: RayJob
          metadata:
            generateName: {{inputs.parameters.job_prefix}}-
            namespace: mlops
            labels:
              workflow: "{{workflow.name}}"
              workflow-uid: "{{workflow.uid}}"
          spec:
            entrypoint: "{{inputs.parameters.entrypoint}}"
            shutdownAfterJobFinishes: true
            ttlSecondsAfterFinished: 300
            rayClusterSpec:
              rayVersion: "2.41.0"  # TODO: bumps
              headGroupSpec:
                rayStartParams:
                  dashboard-host: "0.0.0.0"
                template:
                  spec:
                    containers:
                      - name: ray-head
                        image: "{{inputs.parameters.image}}"
                        resources:
                          requests:
                            cpu: "{{inputs.parameters.cpu}}"
                            memory: "{{inputs.parameters.memory}}"
                          limits:
                            cpu: "{{inputs.parameters.cpu}}"
                            memory: "{{inputs.parameters.memory}}"
                            nvidia.com/gpu: "{{inputs.parameters.gpu}}"
                        envFrom:
                          # Platform config (MLFLOW_TRACKING_URI)
                          - configMapRef:
                              name: mlops-platform-env
                          # Model config (MLFLOW_EXPERIMENT_NAME, MLFLOW_REGISTERED_MODEL_NAME)
                          - configMapRef:
                              name: "{{inputs.parameters.model_configmap}}"
                          # Secrets (AWS_* for MinIO/DVC)
                          - secretRef:
                              name: minio-tenant-secret
                        env:
                          # ===== TRACKING (AI team MUST use these for MLflow tagging) =====
                          - name: ARGO_WORKFLOW_UID
                            value: "{{workflow.uid}}"
                          - name: ARGO_WORKFLOW_NAME
                            value: "{{workflow.name}}"
                          # ===== VERSIONING (links model to code + data) =====
                          - name: DOCKER_IMAGE_TAG
                            value: "{{inputs.parameters.image}}"
                          - name: DVC_DATA_VERSION
                            value: "{{inputs.parameters.dvc_data_version}}"
                          # ===== INFRASTRUCTURE (platform-controlled) =====
                          - name: REPLICAS
                            value: "{{inputs.parameters.replicas}}"
                - groupName: workers
                  replicas: {{inputs.parameters.replicas}}
                  rayStartParams: {}
                  template:
                    spec:
                      containers:
                        - name: ray-worker
                          image: "{{inputs.parameters.image}}"
                          resources:
                            requests:
                              cpu: "{{inputs.parameters.cpu}}"
                              memory: "{{inputs.parameters.memory}}"
                            limits:
                              cpu: "{{inputs.parameters.cpu}}"
                              memory: "{{inputs.parameters.memory}}"
                              nvidia.com/gpu: "{{inputs.parameters.gpu}}"
                          envFrom:
                            - configMapRef:
                                name: mlops-platform-env
                            - configMapRef:
                                name: "{{inputs.parameters.model_configmap}}"
                            - secretRef:
                                name: minio-tenant-secret
                          env:
                            - name: ARGO_WORKFLOW_UID
                              value: "{{workflow.uid}}"
                            - name: ARGO_WORKFLOW_NAME
                              value: "{{workflow.name}}"
                            - name: DOCKER_IMAGE_TAG
                              value: "{{inputs.parameters.image}}"
                            - name: DVC_DATA_VERSION
                              value: "{{inputs.parameters.dvc_data_version}}"
                            - name: REPLICAS
                              value: "{{inputs.parameters.replicas}}"
