# =============================================================================
# Shared Ray Job Templates (Simplified)
# =============================================================================
#
# Uses Argo's native resource template - no kubectl, no scripts.
# Environment configured via static ConfigMaps + dynamic parameters.
#
# Prerequisites:
#   - ConfigMap: mlops-platform-env (MLFLOW_TRACKING_URI)
#   - ConfigMap: <model>-env (model-specific config)
#   - Secret: minio-tenant-secret
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ray-templates
  namespace: mlops
spec:
  templates:
    # =========================================================================
    # MAIN: Submit RayJob and wait for completion
    # =========================================================================
    - name: training-job
      inputs:
        parameters:
          # Job identity
          - name: job_prefix
          - name: image
          - name: entrypoint

          # Model config
          - name: model_configmap
            description: "Model-specific ConfigMap (e.g., wine-classifier-env)"

          # Compute resources
          - name: cpu
            default: "2"
          - name: memory
            default: "4Gi"
          - name: gpu
            default: "0"
          - name: workers
            default: "1"

          # Dynamic run values
          - name: dvc_data_version
            default: ""
          - name: num_workers
            default: "1"

      outputs:
        parameters:
          - name: job_name
            valueFrom:
              jsonPath: "{.metadata.name}"

      resource:
        action: create
        successCondition: status.jobStatus == SUCCEEDED
        failureCondition: status.jobStatus in (FAILED, STOPPED)
        manifest: |
          apiVersion: ray.io/v1
          kind: RayJob
          metadata:
            generateName: {{inputs.parameters.job_prefix}}-
            namespace: mlops
            labels:
              workflow: "{{workflow.name}}"
              workflow-uid: "{{workflow.uid}}"
          spec:
            entrypoint: "{{inputs.parameters.entrypoint}}"
            shutdownAfterJobFinishes: true
            ttlSecondsAfterFinished: 300
            rayClusterSpec:
              rayVersion: "2.41.0"
              headGroupSpec:
                rayStartParams:
                  dashboard-host: "0.0.0.0"
                template:
                  spec:
                    containers:
                      - name: ray-head
                        image: "{{inputs.parameters.image}}"
                        resources:
                          requests:
                            cpu: "{{inputs.parameters.cpu}}"
                            memory: "{{inputs.parameters.memory}}"
                          limits:
                            cpu: "{{inputs.parameters.cpu}}"
                            memory: "{{inputs.parameters.memory}}"
                            nvidia.com/gpu: "{{inputs.parameters.gpu}}"
                        envFrom:
                          - configMapRef:
                              name: mlops-platform-env
                          - configMapRef:
                              name: "{{inputs.parameters.model_configmap}}"
                          - secretRef:
                              name: minio-tenant-secret
                        env:
                          - name: ARGO_WORKFLOW_UID
                            value: "{{workflow.uid}}"
                          - name: ARGO_WORKFLOW_NAME
                            value: "{{workflow.name}}"
                          - name: DVC_DATA_VERSION
                            value: "{{inputs.parameters.dvc_data_version}}"
                          - name: DOCKER_IMAGE_TAG
                            value: "{{inputs.parameters.image}}"
                          - name: NUM_WORKERS
                            value: "{{inputs.parameters.num_workers}}"
              workerGroupSpecs:
                - groupName: workers
                  replicas: {{inputs.parameters.workers}}
                  rayStartParams: {}
                  template:
                    spec:
                      containers:
                        - name: ray-worker
                          image: "{{inputs.parameters.image}}"
                          resources:
                            requests:
                              cpu: "{{inputs.parameters.cpu}}"
                              memory: "{{inputs.parameters.memory}}"
                            limits:
                              cpu: "{{inputs.parameters.cpu}}"
                              memory: "{{inputs.parameters.memory}}"
                              nvidia.com/gpu: "{{inputs.parameters.gpu}}"
                          envFrom:
                            - configMapRef:
                                name: mlops-platform-env
                            - configMapRef:
                                name: "{{inputs.parameters.model_configmap}}"
                            - secretRef:
                                name: minio-tenant-secret
                          env:
                            - name: ARGO_WORKFLOW_UID
                              value: "{{workflow.uid}}"
                            - name: ARGO_WORKFLOW_NAME
                              value: "{{workflow.name}}"
                            - name: DVC_DATA_VERSION
                              value: "{{inputs.parameters.dvc_data_version}}"
                            - name: DOCKER_IMAGE_TAG
                              value: "{{inputs.parameters.image}}"
                            - name: NUM_WORKERS
                              value: "{{inputs.parameters.num_workers}}"
