# Fashion-Mnist-Classifier - Complete Service Definition
---
# RayService for model serving
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: fashion-mnist-classifier-service
  namespace: models
  labels:
    app.kubernetes.io/name: fashion-mnist-classifier
spec:
  serviceUnhealthySecondThreshold: 900
  deploymentUnhealthySecondThreshold: 300
  serveConfigV2: |
    applications:
      - name: fashion-mnist-classifier-api
        import_path: src.serving.serve:app_builder
        route_prefix: /models/custom/fashion-mnist-classifier
        deployments:
          - name: FashionMNISTClassifier
            user_config:
              model_uri: "models:/prod.fashion-mnist-classifier/2"
            num_replicas: auto  # Enable autoscaling!
            max_ongoing_requests: 5
            autoscaling_config:
              target_ongoing_requests: 2
              min_replicas: 1
              max_replicas: 3
              upscale_delay_s: 10      # Fast response for demos
              downscale_delay_s: 30    # Quick scale-down for demos
            ray_actor_options:
              num_cpus: 1
              memory: 3221225472  # 3GB
    http_options:
      host: "0.0.0.0"
      port: 8000
  rayClusterConfig:
    rayVersion: '2.48.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
        metrics-export-port: '8080'
        object-store-memory: '1073741824' # 1GB for object store
      template:
        spec:
          containers:
            - name: ray-head
              image: opencloudhuborg/fashion-mnist-classifier-serving:main-f079944
              imagePullPolicy: Always
              startupProbe:
                httpGet:
                  path: /api/gcs_healthz
                  port: 8265
                initialDelaySeconds: 10
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 18 # 3 minutes total
              readinessProbe:
                httpGet:
                  path: /api/gcs_healthz
                  port: 8265
                initialDelaySeconds: 5
                periodSeconds: 5
                timeoutSeconds: 3
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /api/gcs_healthz
                  port: 8265
                initialDelaySeconds: 180
                periodSeconds: 30
                timeoutSeconds: 10
                failureThreshold: 5
              ports:
                - containerPort: 8000
                  name: serve
                  protocol: TCP
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
                - containerPort: 8265
                  name: dashboard
                  protocol: TCP
              resources:
                requests:
                  cpu: "1500m"
                  memory: "4Gi"
                limits:
                  cpu: "3"
                  memory: "6Gi"
              env:
                - name: MLFLOW_TRACKING_URI
                  value: "http://mlflow.mlops.svc.cluster.local:80"
                - name: RAY_GRAFANA_HOST
                  value: "http://grafana.observability.svc.cluster.local:80"
                - name: RAY_PROMETHEUS_HOST
                  value: "http://prometheus-server.observability.svc.cluster.local:80"
                - name: RAY_GRAFANA_IFRAME_HOST
                  value: "https://grafana.internal.opencloudhub.org"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: minio-tenant-secret
                      key: accesskey
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-tenant-secret
                      key: secretkey
                - name: AWS_ENDPOINT_URL
                  value: "https://minio-api.internal.opencloudhub.org"
    workerGroupSpecs:
      - groupName: serving-workers
        replicas: 2
        minReplicas: 1
        maxReplicas: 2
        numOfHosts: 1
        template:
          spec:
            containers:
              - name: ray-worker
                image: opencloudhuborg/fashion-mnist-classifier-serving:main-f079944
                imagePullPolicy: Always
                readinessProbe:
                  exec:
                    command:
                      - bash
                      - -c
                      - wget --tries 1 -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 2
                  successThreshold: 1
                  failureThreshold: 3
                resources:
                  requests:
                    cpu: "1500m"
                    memory: "4Gi"
                  limits:
                    cpu: "3"
                    memory: "6Gi"
                env:
                  - name: MLFLOW_TRACKING_URI
                    value: "http://mlflow.mlops.svc.cluster.local:80"
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: minio-tenant-secret
                        key: accesskey
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: minio-tenant-secret
                        key: secretkey
                  - name: AWS_ENDPOINT_URL
                    value: "https://minio-api.internal.opencloudhub.org"
---
# HTTPRoute for model API (external access)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fashion-mnist-classifier-api-route
  namespace: models
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress
  hostnames:
    - "api.opencloudhub.org"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /models/custom/fashion-mnist-classifier
      backendRefs:
        - group: ''
          kind: Service
          name: fashion-mnist-classifier-service-serve-svc
          port: 8000
          weight: 1

---
# HTTPRoute for Ray Dashboard
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fashion-mnist-classifier-dashboard-route
  namespace: models
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress
  hostnames:
    - "fashion-mnist-classifier.dashboard.opencloudhub.org"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - group: ''
          kind: Service
          name: fashion-mnist-classifier-service-head-svc
          port: 8265
          weight: 1
