# Wine Classifier - Complete Service Definition
---
# RayService for model serving
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: wine-classifier-service
  namespace: models
  labels:
    app.kubernetes.io/name: wine-classifier
spec:
  serviceUnhealthySecondThreshold: 900
  deploymentUnhealthySecondThreshold: 300
  serveConfigV2: |
    applications:
      - name: wine-classifier-api
        import_path: src.serving.serve:app_builder
        route_prefix: /models/custom/wine-classifier
        deployments:
          - name: WineClassifier
            user_config:
              model_uri: "models:/prod.wine-classifier/@champion"
            num_replicas: 2
            max_ongoing_requests: 5
            ray_actor_options:
              num_cpus: 0.5
  rayClusterConfig:
    rayVersion: "2.48.0"
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
        metrics-export-port: "8080"
      template:
        spec:
          containers:
            - name: ray-head
              image: opencloudhuborg/wine-classifier-serving:main-d36b8f0
              imagePullPolicy: Always
              ports:
                - containerPort: 8000
                  name: serve
                  protocol: TCP
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
                - containerPort: 8265
                  name: dashboard
                  protocol: TCP
              resources:
                requests:
                  cpu: "1"
                  memory: "2Gi"
                limits:
                  cpu: "2"
                  memory: "3Gi"
              env:
                - name: MLFLOW_TRACKING_URI
                  value: "http://mlflow.mlops.svc.cluster.local:80"
                - name: RAY_GRAFANA_HOST
                  value: "http://grafana.observability.svc.cluster.local:80"
                - name: RAY_PROMETHEUS_HOST
                  value: "http://prometheus-server.observability.svc.cluster.local:80"
                - name: RAY_GRAFANA_IFRAME_HOST
                  value: "https://grafana.internal.opencloudhub.org"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: minio-tenant-secret
                      key: accesskey
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-tenant-secret
                      key: secretkey
                - name: AWS_ENDPOINT_URL
                  value: "https://minio-api.internal.opencloudhub.org"
    workerGroupSpecs:
      - groupName: serving-workers
        replicas: 1
        minReplicas: 1
        maxReplicas: 2
        numOfHosts: 1
        template:
          spec:
            containers:
              - name: ray-worker
                image: opencloudhuborg/wine-classifier-serving:main-d36b8f0
                imagePullPolicy: Always
                # Override the readiness probe - workers don't run Serve
                readinessProbe:
                  exec:
                    command:
                      - bash
                      - -c
                      - wget --tries 1 -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 2
                  successThreshold: 1
                  failureThreshold: 3
                resources:
                  requests:
                    cpu: "1"
                    memory: "2Gi"
                  limits:
                    cpu: "2"
                    memory: "3Gi"
                env:
                  - name: MLFLOW_TRACKING_URI
                    value: "http://mlflow.mlops.svc.cluster.local:80"
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: minio-tenant-secret
                        key: accesskey
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: minio-tenant-secret
                        key: secretkey
                  - name: AWS_ENDPOINT_URL
                    value: "https://minio-api.internal.opencloudhub.org"
---
# HTTPRoute for model API (external access)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wine-classifier-api-route
  namespace: models
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress
  hostnames:
    - "api.opencloudhub.org"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /models/custom/wine-classifier
      timeouts:
        request: 30s
      backendRefs:
        - group: ""
          kind: Service
          name: wine-classifier-service-serve-svc
          port: 8000
          weight: 1

---
# HTTPRoute for Ray Dashboard
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wine-classifier-dashboard-route
  namespace: models
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress
  hostnames:
    - "wine-classifier.dashboard.opencloudhub.org"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - group: ""
          kind: Service
          name: wine-classifier-service-head-svc
          port: 8265
          weight: 1
