---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-controller-secret-reader
  namespace: arc-runners
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-controller-secret-reader
  namespace: arc-runners
subjects:
  - kind: ServiceAccount
    name: arc-gha-rs-controller
    namespace: arc-systems
roleRef:
  kind: Role
  name: arc-controller-secret-reader
  apiGroup: rbac.authorization.k8s.io
