apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: models-job-secrets
  namespace: mlops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: models-job-secrets
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .accesskey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretkey }}"
        AWS_ENDPOINT_URL: "http://minio.minio-tenant.svc.cluster.local:80"
  data:
    - secretKey: accesskey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: secretkey
