apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: data-pipeline
  namespace: mlops
  annotations:
    workflows.argoproj.io/title: '**Data Pipeline**'
    workflows.argoproj.io/description: 'Run DVC pipelines, push, commit, tag, and trigger embeddings.'
spec:
  serviceAccountName: workflow-executor

  arguments:
    parameters:
      - name: pipelines
        value: '["emotion","fashion-mnist","wine-quality","opencloudhub-readmes-download"]'
      - name: force
        value: "false"
      - name: bump_type
        value: "patch"
      - name: is_automated
        value: "false"
      - name: trigger_embeddings
        value: "true"
      - name: image
        value: "opencloudhuborg/data-registry-pipelines:latest"

  entrypoint: main

  templates:
    - name: main
      steps:
        # 1. Run pipelines in parallel
        - - name: run-pipelines
            templateRef:
              name: data-templates
              template: run-dvc-pipeline
            arguments:
              parameters:
                - name: pipeline_name
                  value: "{{item}}"
                - name: image
                  value: "{{workflow.parameters.image}}"
                - name: force
                  value: "{{workflow.parameters.force}}"
            withParam: "{{workflow.parameters.pipelines}}"

        # 2. Push to remote
        - - name: push-data
            templateRef:
              name: data-templates
              template: dvc-push
            arguments:
              parameters:
                - name: image
                  value: "{{workflow.parameters.image}}"

        # 3. Detect changes
        - - name: detect-changes
            templateRef:
              name: data-templates
              template: detect-dvc-changes

        # 4. Commit if changes
        - - name: commit
            templateRef:
              name: git-templates
              template: commit-and-push
            arguments:
              parameters:
                - name: message
                  value: "chore: update data [skip ci]"
            when: "{{steps.detect-changes.outputs.parameters.has_changes}} == true"

        # 5. Create tags for changed datasets
        - - name: create-tags
            templateRef:
              name: git-templates
              template: create-tag
            arguments:
              parameters:
                - name: tag_prefix
                  value: "{{item}}"
                - name: bump_type
                  value: "{{workflow.parameters.bump_type}}"
                - name: is_automated
                  value: "{{workflow.parameters.is_automated}}"
            withParam: "{{steps.detect-changes.outputs.parameters.changed_datasets}}"
            when: "{{steps.detect-changes.outputs.parameters.has_changes}} == true"

        # 6. Run embeddings if readmes changed
        - - name: embeddings
            template: run-embeddings
            when: "{{workflow.parameters.trigger_embeddings}} == true && {{steps.detect-changes.outputs.parameters.has_changes}} == true"

    - name: run-embeddings
      steps:
        # Check if opencloudhub-readmes is in changed datasets
        - - name: check-readmes
            template: contains-dataset
            arguments:
              parameters:
                - name: datasets
                  value: "{{workflow.outputs.parameters.changed_datasets}}"
                - name: target
                  value: "opencloudhub-readmes"

        # Get the tag we just created
        - - name: get-tag
            templateRef:
              name: git-templates
              template: get-latest-tag
            arguments:
              parameters:
                - name: tag_prefix
                  value: "opencloudhub-readmes"
            when: "{{steps.check-readmes.outputs.result}} == true"

        # Run embeddings pipeline
        - - name: run
            templateRef:
              name: embeddings-pipeline
              template: main
            arguments:
              parameters:
                - name: data_version
                  value: "{{steps.get-tag.outputs.parameters.latest_tag}}"
                - name: compute_type
                  value: "cpu-small"
                - name: image
                  value: "{{workflow.parameters.image}}"
            when: "{{steps.check-readmes.outputs.result}} == true"

    - name: contains-dataset
      inputs:
        parameters:
          - name: datasets
          - name: target
      script:
        image: alpine:latest
        command: [sh]
        source: |
          apk add --no-cache jq >/dev/null 2>&1
          echo '{{inputs.parameters.datasets}}' | jq -e 'index("{{inputs.parameters.target}}") != null' >/dev/null && echo -n "true" || echo -n "false"
