apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-tenant-secret-es
  namespace: minio-tenant
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-tenant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.env: |
          export MINIO_ROOT_USER={{ .accesskey }}
          export MINIO_ROOT_PASSWORD={{ .secretkey }}
        accesskey: "{{ .accesskey }}"
        secretkey: "{{ .secretkey }}"
  data:
    - secretKey: accesskey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: secretkey
