apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-tenant-monitor
  namespace: minio-tenant
  labels:
    release: k8s-monitoring
spec:
  selector:
    matchLabels:
      app: minio
  endpoints:
  - port: http-minio
    path: /minio/v2/metrics/cluster
    interval: 30s
    basicAuth:
      username:
        name: minio-tenant-secret
        key: accesskey
      password:
        name: minio-tenant-secret
        key: secretkey
