# =============================================================================
# Testing Templates
# =============================================================================
#
# Model testing templates for staging validation.
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: testing-templates
  namespace: mlops
  annotations:
    workflows.argoproj.io/description: "Model testing templates"
spec:
  templates:
    # =========================================================================
    # TEST STAGING MODEL
    # =========================================================================
    - name: test-staging-model
      inputs:
        parameters:
          - name: model_name
          - name: staging_version
          - name: mlflow_tracking_uri
            default: "http://mlflow.mlops.svc.cluster.local:80"
      outputs:
        parameters:
          - name: test_passed
            valueFrom:
              path: /tmp/test_passed.txt
      script:
        image: ghcr.io/mlflow/mlflow:v2.18.0
        command: [python]
        source: |
          import os

          model_name = "{{inputs.parameters.model_name}}"
          staging_version = "{{inputs.parameters.staging_version}}"
          mlflow_uri = "{{inputs.parameters.mlflow_tracking_uri}}"

          print(f"🧪 Testing staging model: staging.{model_name}/v{staging_version}")
          print(f"   MLflow: {mlflow_uri}")
          print("")

          # TODO: Implement actual model tests
          # For now, basic validation that model exists and is loadable

          from mlflow import MlflowClient
          import mlflow

          mlflow.set_tracking_uri(mlflow_uri)
          client = MlflowClient(mlflow_uri)

          try:
              # Verify model version exists
              mv = client.get_model_version(f"staging.{model_name}", staging_version)
              print(f"✅ Model version exists: {mv.name}/v{mv.version}")
              print(f"   Status: {mv.status}")
              print(f"   Run ID: {mv.run_id}")

              # Basic validation passed
              test_passed = True
              print("")
              print("✅ All tests passed")

          except Exception as e:
              print(f"❌ Test failed: {e}")
              test_passed = False

          with open("/tmp/test_passed.txt", "w") as f:
              f.write("true" if test_passed else "false")
