# =============================================================================
# Testing Templates
# =============================================================================
#
# Model testing templates for staging validation.
# ⚠️ Currently just dummy implementation, run load tests or integration tests or deploy in staging environment here if needed
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: testing-templates
  namespace: mlops
  annotations:
    workflows.argoproj.io/description: "Model testing templates"
spec:
  templates:
    # =========================================================================
    # TEST STAGING MODEL
    # =========================================================================
    - name: test-staging-model
      inputs:
        parameters:
          - name: model_name
          - name: staging_version
          - name: mlflow_tracking_uri
            default: "http://mlflow.mlops.svc.cluster.local:80"
      outputs:
        parameters:
          - name: test_passed
            valueFrom:
              path: /tmp/test_passed.txt
        artifacts:
          - name: test-report
            path: /tmp/test-report.md
            archive:
              none: {}
      script:
        image: ghcr.io/mlflow/mlflow:v2.18.0
        command: [python]
        source: |
          from mlflow import MlflowClient
          import random

          model_name = "{{inputs.parameters.model_name}}"
          staging_version = "{{inputs.parameters.staging_version}}"
          mlflow_uri = "{{inputs.parameters.mlflow_tracking_uri}}"

          client = MlflowClient(mlflow_uri)

          # Simulate test execution (dummy implementation)
          tests = {
              "model_loading": True,
              "schema_validation": True,
              "smoke_test": True,
              "latency_ms": random.uniform(10, 50),
              "sample_accuracy": random.uniform(0.85, 0.95),
          }

          all_passed = (
              tests["model_loading"] and
              tests["schema_validation"] and
              tests["smoke_test"] and
              tests["latency_ms"] < 100 and
              tests["sample_accuracy"] > 0.8
          )

          status = "✅ ALL TESTS PASSED" if all_passed else "❌ TESTS FAILED"
          loading = '✓' if tests['model_loading'] else '✗'
          schema = '✓' if tests['schema_validation'] else '✗'
          smoke = '✓' if tests['smoke_test'] else '✗'
          latency = f"{tests['latency_ms']:.1f}ms"
          accuracy = f"{tests['sample_accuracy']:.1%}"

          lines = [
              "",
              "##################################################",
              "🧪 TEST STAGING MODEL",
              "##################################################",
              "",
              f"  Model ........ staging.{model_name}",
              f"  Version ...... v{staging_version}",
              f"  MLflow ....... {mlflow_uri}",
              "",
              "  Tests",
              f"    Model Loading ..... {loading}",
              f"    Schema Validation . {schema}",
              f"    Smoke Test ........ {smoke}",
              f"    Latency ........... {latency} (<100ms)",
              f"    Sample Accuracy ... {accuracy} (>80%)",
              "",
              "------------------------------------------",
              status,
              "------------------------------------------",
              "⚠️ Dummy test suite - replace with real tests",
              "##################################################",
              "##################################################",
              ""
          ]
          OUTPUT = "\n".join(lines)

          print(OUTPUT)

          with open("/tmp/test-report.md", "w") as f:
              f.write(OUTPUT)

          with open("/tmp/test_passed.txt", "w") as f:
              f.write("true" if all_passed else "false")

          if not all_passed:
              exit(1)
