apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret-es
  namespace: ai
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: dockerhub-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: platform/docker/registry
      property: username
  - secretKey: password
    remoteRef:
      key: platform/docker/registry
      property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dvc-config-es
  namespace: ai
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: dvc-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config: |
          ['remote "minio"']
              access_key_id = {{ .accesskey }}
              secret_access_key = {{ .secretkey }}
  data:
    - secretKey: accesskey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: secretkey

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-credentials
  namespace: ai
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitops-repo
    creationPolicy: Owner
    # Add template with required ArgoCD repository secret format
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
  - secretKey: url
    remoteRef:
      key: platform/gitops/repos/gitops
      property: url
  - secretKey: type
    remoteRef:
      key: platform/gitops/repos/gitops
      property: type
  - secretKey: sshPrivateKey
    remoteRef:
      key: platform/gitops/repos/gitops
      property: sshPrivateKey
