apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
- https://github.com/argoproj/argo-workflows/releases/download/v3.7.3/namespace-install.yaml

patches:
- target:
    kind: Namespace
    name: argo
  patch: |-
    - op: replace
      path: /metadata/name
      value: ai
