apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
- https://github.com/argoproj/argo-workflows/releases/download/v3.7.3/namespace-install.yaml
- http-route.yaml

patches:
- target:
    kind: Namespace
    name: argo
  patch: |-
    - op: replace
      path: /metadata/name
      value: ai
# Disable AUuh
- target:
    kind: Deployment
    name: argo-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --auth-mode=server
# NO TLS, # TODO: do we want in prod?
patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --secure=false
