apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: demo-app-db-pooler
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: cnpg
spec:
  cluster:
    name: demo-app-db-cluster
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "100"
      default_pool_size: "10"
      ignore_startup_parameters: "search_path"
