apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-templates
  namespace: mlops
  annotations:
    workflows.argoproj.io/description: 'Git utilities for commits, pushes and tags.'
spec:
  serviceAccountName: workflow-executor

  templates:
    # ----------------------------------------------------------------------
    # Create a version tag
    # ----------------------------------------------------------------------
    - name: create-tag
      inputs:
        parameters:
          - name: repo_url
            default: "git@github.com:OpenCloudHub/data-registry.git"
          - name: tag_prefix
          - name: bump_type
            default: "patch"
          - name: is_automated
            default: "false"
          - name: message
            default: ""
      outputs:
        parameters:
          - name: new_tag
            valueFrom:
              path: /tmp/new_tag.txt
      volumes:
        - name: git-secret
          secret:
            secretName: gitops-repo
      script:
        image: alpine/git:latest
        command: [sh]
        volumeMounts:
          - name: git-secret
            mountPath: /mnt/secrets
            readOnly: true
        source: |
          set -e

          mkdir -p ~/.ssh
          cat /mnt/secrets/sshPrivateKey > ~/.ssh/id_ed25519
          echo "" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          TAG_PREFIX="{{inputs.parameters.tag_prefix}}"
          BUMP_TYPE="{{inputs.parameters.bump_type}}"
          IS_AUTOMATED="{{inputs.parameters.is_automated}}"
          MESSAGE="{{inputs.parameters.message}}"

          git clone --depth 20 "{{inputs.parameters.repo_url}}" /tmp/repo
          cd /tmp/repo

          git config user.name "Argo Workflow"
          git config user.email "workflow@opencloudhub.org"

          LATEST=$(git tag -l "${TAG_PREFIX}-v*" --sort=-version:refname 2>/dev/null | head -n1 || echo "")

          if [ -z "$LATEST" ]; then
            VERSION="1.0.0"
          else
            CURRENT=$(echo "$LATEST" | sed "s/${TAG_PREFIX}-v//" | sed 's/-automated//')
            MAJOR=$(echo "$CURRENT" | cut -d. -f1)
            MINOR=$(echo "$CURRENT" | cut -d. -f2)
            PATCH=$(echo "$CURRENT" | cut -d. -f3)

            case "$BUMP_TYPE" in
              major) VERSION="$((MAJOR + 1)).0.0" ;;
              minor) VERSION="${MAJOR}.$((MINOR + 1)).0" ;;
              patch) VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))" ;;
            esac
          fi

          [ "$IS_AUTOMATED" = "true" ] && SUFFIX="-automated" || SUFFIX=""
          NEW_TAG="${TAG_PREFIX}-v${VERSION}${SUFFIX}"
          [ -z "$MESSAGE" ] && MESSAGE="${TAG_PREFIX} v${VERSION}"

          git tag -a "$NEW_TAG" -m "$MESSAGE"
          git push origin "$NEW_TAG"

          echo "✅ $NEW_TAG"
          echo "$NEW_TAG" > /tmp/new_tag.txt

    # ----------------------------------------------------------------------
    # Get latest tag for a prefix
    # ----------------------------------------------------------------------
    - name: get-latest-tag
      inputs:
        parameters:
          - name: repo_url
            default: "git@github.com:OpenCloudHub/data-registry.git"
          - name: tag_prefix
      outputs:
        parameters:
          - name: latest_tag
            valueFrom:
              path: /tmp/latest_tag.txt
      volumes:
        - name: git-secret
          secret:
            secretName: gitops-repo
      script:
        image: alpine/git:latest
        command: [sh]
        volumeMounts:
          - name: git-secret
            mountPath: /mnt/secrets
            readOnly: true
        source: |
          set -e

          mkdir -p ~/.ssh
          cat /mnt/secrets/sshPrivateKey > ~/.ssh/id_ed25519
          echo "" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git clone --depth 20 "{{inputs.parameters.repo_url}}" /tmp/repo
          cd /tmp/repo

          TAG=$(git tag -l "{{inputs.parameters.tag_prefix}}-v*" --sort=-version:refname | head -n1 || echo "")
          echo "$TAG" > /tmp/latest_tag.txt
          echo "Latest: ${TAG:-none}"

    # ----------------------------------------------------------------------
    # Commit and push changes
    # ----------------------------------------------------------------------
    - name: commit-and-push
      inputs:
        parameters:
          - name: repo_url
            default: "git@github.com:OpenCloudHub/data-registry.git"
          - name: branch
            default: "main"
          - name: message
            default: "chore: update data [skip ci]"
      volumes:
        - name: git-secret
          secret:
            secretName: gitops-repo
      script:
        image: alpine/git:latest
        command: [sh]
        volumeMounts:
          - name: git-secret
            mountPath: /mnt/secrets
            readOnly: true
        source: |
          set -e

          mkdir -p ~/.ssh
          cat /mnt/secrets/sshPrivateKey > ~/.ssh/id_ed25519
          echo "" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git clone "{{inputs.parameters.repo_url}}" /tmp/repo
          cd /tmp/repo
          git checkout "{{inputs.parameters.branch}}"

          git config user.name "Argo Workflow"
          git config user.email "workflow@opencloudhub.org"

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "{{inputs.parameters.message}}"
            git push origin "{{inputs.parameters.branch}}"
            echo "✅ Pushed"
          else
            echo "ℹ️  No changes"
          fi
