apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mlops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # TODO: adjust this
  description: mlops wide acccess for admin users only
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
