# =============================================================================
# MLOps Pipeline
# =============================================================================
#
# End-to-end ML lifecycle orchestration: train → evaluate → promote → deploy
#
# Phases:
#   1. Map compute type to resources (compute-templates)
#   2. Training via Ray (ray-templates)
#   3. Compare to production and promote to staging (mlflow-templates)
#   4. Approval gate (manual mode only)
#   5. Promote staging to production (mlflow-templates)
#   6. Deploy via GitOps (deployment-templates)
#
# Parameters:
#   model_name        - Model identifier (e.g., wine-classifier)
#   experiment_name   - MLflow experiment name
#   training_image    - Docker image for training
#   serving_image     - Docker image for serving
#   dvc_data_version  - DVC tag for training data
#   compute_type      - Resource profile (cpu-small, gpu-medium, etc.)
#   approval_mode     - "automatic" or "manual" (requires human approval)
#
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-pipeline
  namespace: mlops
  annotations:
    workflows.argoproj.io/title: "**MLOPS Pipeline**"
    workflows.argoproj.io/description: "End-to-end MLOps pipeline: Train -> Compare -> Promote -> Deploy"
spec:
  serviceAccountName: workflow-executor
  entrypoint: main

  arguments:
    parameters:
      # Model identity
      - name: model_name
        description: "Unique model identifier used for MLflow registration and K8s resources (e.g., wine-classifier)"
      - name: experiment_name
        description: "MLflow experiment name for tracking training runs"

      # Images
      - name: training_image
        description: "Docker image containing training code and dependencies"
      - name: serving_image
        description: "Docker image for model serving (updated in GitOps repo on deploy)"
      - name: training_entrypoint
        description: "Command to execute training script (e.g., python src/training/train.py)"
      - name: training_args
        description: "Additional arguments passed to the training entrypoint"
        default: ""

      # Data
      - name: dvc_data_version
        description: "DVC tag specifying which version of training data to use"

      # Compute (uses compute-templates mapping)
      - name: compute_type
        description: "Resource profile for Ray cluster (maps to CPU, memory, GPU, replicas)"
        enum:
          [
            cpu-small,
            cpu-small-distributed,
            cpu-medium,
            cpu-large,
            gpu-small,
            gpu-medium,
            gpu-large,
          ]

      # Comparison
      - name: comparison_metric
        description: "MLflow metric name to compare between CI model and production champion"
        default: "accuracy"
      - name: comparison_higher_is_better
        description: "Are higher metric values better"
        default: "true"
      - name: comparison_threshold
        description: "Minimum improvement required over champion to promote (e.g., 0.05 = 5%)"
        default: "0.05"

      # Approval
      - name: approval_mode
        description: "Set to 'manual' to require human approval before production deployment"
        default: "automatic"

  templates:
    - name: main
      dag:
        tasks:
          # Phase 1: Map compute type to resources
          - name: map-compute
            templateRef:
              name: compute-templates
              template: map-compute-config
            arguments:
              parameters:
                - name: compute_type
                  value: "{{workflow.parameters.compute_type}}"

          # Phase 2: Training
          - name: train
            depends: "map-compute.Succeeded"
            templateRef:
              name: ray-templates
              template: submit-and-stream-rayjob
            arguments:
              parameters:
                - name: job_prefix
                  value: "{{workflow.parameters.model_name}}-train"
                - name: image
                  value: "{{workflow.parameters.training_image}}"
                - name: entrypoint
                  value: "{{workflow.parameters.training_entrypoint}} {{workflow.parameters.training_args}}"
                - name: model_configmap
                  value: "{{workflow.parameters.model_name}}-env"
                - name: cpu
                  value: "{{tasks.map-compute.outputs.parameters.cpu_request}}"
                - name: memory
                  value: "{{tasks.map-compute.outputs.parameters.memory_request}}"
                - name: gpu
                  value: "{{tasks.map-compute.outputs.parameters.gpu}}"
                - name: replicas
                  value: "{{tasks.map-compute.outputs.parameters.replicas}}"
                - name: dvc_data_version
                  value: "{{workflow.parameters.dvc_data_version}}"

          # Phase 3: Compare and promote to staging
          - name: compare-and-promote
            depends: "train.Succeeded"
            templateRef:
              name: mlflow-templates
              template: compare-to-production-and-promote-to-staging
            arguments:
              parameters:
                - name: model_name
                  value: "{{workflow.parameters.model_name}}"
                - name: metric_name
                  value: "{{workflow.parameters.comparison_metric}}"
                - name: higher_is_better
                  value: "{{workflow.parameters.comparison_higher_is_better}}"
                - name: threshold
                  value: "{{workflow.parameters.comparison_threshold}}"

          # Phase 4: Test staging model
          - name: test-staging
            depends: "compare-and-promote.Succeeded"
            when: "'{{tasks.compare-and-promote.outputs.parameters.promoted}}' == 'true'"
            templateRef:
              name: testing-templates
              template: test-staging-model
            arguments:
              parameters:
                - name: model_name
                  value: "{{workflow.parameters.model_name}}"
                - name: staging_version
                  value: "{{tasks.compare-and-promote.outputs.parameters.staging_version}}"

          # Phase 5: Approval gate (manual mode only)
          - name: approval
            depends: "test-staging.Succeeded"
            when: "'{{workflow.parameters.approval_mode}}' == 'manual'"
            template: approval-gate

          # Phase 6: Promote to production
          - name: promote-production
            depends: "test-staging.Succeeded && (approval.Succeeded || approval.Skipped)"
            when: "'{{workflow.parameters.approval_mode}}' == 'automatic' || '{{tasks.approval.outputs.parameters.approve}}' == 'YES'"
            templateRef:
              name: mlflow-templates
              template: promote-staging-to-production
            arguments:
              parameters:
                - name: model_name
                  value: "{{workflow.parameters.model_name}}"
                - name: staging_version
                  value: "{{tasks.compare-and-promote.outputs.parameters.staging_version}}"

          # Phase 7: Deploy
          - name: deploy
            depends: "promote-production.Succeeded"
            templateRef:
              name: deployment-templates
              template: deploy-model
            arguments:
              parameters:
                - name: model_name
                  value: "{{workflow.parameters.model_name}}"
                - name: model_uri
                  value: "models:/prod.{{workflow.parameters.model_name}}/@champion"
                - name: serving_image
                  value: "{{workflow.parameters.serving_image}}"

    # =========================================================================
    # APPROVAL GATE
    # =========================================================================
    - name: approval-gate
      inputs:
        parameters:
          - name: approve
            default: "NO"
            enum: ["YES", "NO"]
      outputs:
        parameters:
          - name: approve
            valueFrom:
              supplied: {}
      suspend: {}
