# =============================================================================
# MLOps Pipeline
# =============================================================================
#
# End-to-end ML lifecycle orchestration: train → evaluate → promote → deploy
#
# Phases:
#   1. Map compute type to resources (compute-templates)
#   2. Training via Ray (ray-templates)
#   3. Compare to production and promote to staging (mlflow-templates)
#   4. Approval gate (manual mode only)
#   5. Promote staging to production (mlflow-templates)
#   6. Deploy via GitOps (deployment-templates)
#
# Parameters:
#   model_name        - Model identifier (e.g., wine-classifier)
#   experiment_name   - MLflow experiment name
#   training_image    - Docker image for training
#   serving_image     - Docker image for serving
#   dvc_data_version  - DVC tag for training data
#   compute_type      - Resource profile (cpu-small, gpu-medium, etc.)
#   approval_mode     - "automatic" or "manual" (requires human approval)
#
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-pipeline
  namespace: mlops
  annotations:
    workflows.argoproj.io/description: "End-to-end MLOps pipeline"
spec:
  serviceAccountName: workflow-executor
  entrypoint: main

  arguments:
    parameters:
      # Model identity
      - name: model_name
      - name: experiment_name

      # Images
      - name: training_image
      - name: serving_image
      - name: training_entrypoint
      - name: training_args
        default: ""

      # Data
      - name: dvc_data_version

      # Compute (uses compute-templates mapping)
      - name: compute_type
        enum:
          [
            cpu-small,
            cpu-small-distributed,
            cpu-medium,
            cpu-large,
            gpu-small,
            gpu-medium,
            gpu-large,
          ]

      # Comparison
      - name: comparison_metric
        default: "accuracy"
      - name: comparison_higher_is_better
        default: "true"
      - name: comparison_threshold
        default: "0.05"

      # Approval
      - name: approval_mode
        default: "automatic"

  templates:
    - name: main
      steps:
        # Phase 1: Map compute type to resources
        - - name: map-compute
            templateRef:
              name: compute-templates
              template: map-compute-config
            arguments:
              parameters:
                - name: compute_type
                  value: "{{workflow.parameters.compute_type}}"

        # Phase 2: Training
        - - name: train
            templateRef:
              name: ray-templates
              template: training-job
            arguments:
              parameters:
                - name: job_prefix
                  value: "{{workflow.parameters.model_name}}-train"
                - name: image
                  value: "{{workflow.parameters.training_image}}"
                - name: entrypoint
                  value: "{{workflow.parameters.training_entrypoint}} {{workflow.parameters.training_args}}"
                - name: model_configmap
                  value: "{{workflow.parameters.model_name}}-env"
                - name: cpu
                  value: "{{steps.map-compute.outputs.parameters.cpu_request}}"
                - name: memory
                  value: "{{steps.map-compute.outputs.parameters.memory_request}}"
                - name: gpu
                  value: "{{steps.map-compute.outputs.parameters.gpu}}"
                - name: replicas
                  value: "{{steps.map-compute.outputs.parameters.replicas}}"
                - name: dvc_data_version
                  value: "{{workflow.parameters.dvc_data_version}}"

        # Phase 3: Compare and promote to staging
        - - name: compare-and-promote
            templateRef:
              name: mlflow-templates
              template: compare-to-production-and-promote-to-staging
            arguments:
              parameters:
                - name: model_name
                  value: "{{workflow.parameters.model_name}}"
                - name: metric_name
                  value: "{{workflow.parameters.comparison_metric}}"
                - name: higher_is_better
                  value: "{{workflow.parameters.comparison_higher_is_better}}"
                - name: threshold
                  value: "{{workflow.parameters.comparison_threshold}}"

        # Phase 4: Approval gate (manual mode only)
        - - name: approval
            template: approval-gate
            when: "'{{workflow.parameters.approval_mode}}' == 'manual' && '{{steps.compare-and-promote.outputs.parameters.promoted}}' == 'true'"

        # Phase 5: Promote to production
        - - name: promote-production
            templateRef:
              name: mlflow-templates
              template: promote-staging-to-production
            arguments:
              parameters:
                - name: model_name
                  value: "{{workflow.parameters.model_name}}"
                - name: staging_version
                  value: "{{steps.compare-and-promote.outputs.parameters.staging_version}}"
            when: "'{{steps.compare-and-promote.outputs.parameters.promoted}}' == 'true'"

        # Phase 6: Deploy
        - - name: deploy
            templateRef:
              name: deployment-templates
              template: deploy-model
            arguments:
              parameters:
                - name: model_name
                  value: "{{workflow.parameters.model_name}}"
                - name: model_uri
                  value: "models:/prod.{{workflow.parameters.model_name}}/@champion"
                - name: serving_image
                  value: "{{workflow.parameters.serving_image}}"
            when: "'{{steps.compare-and-promote.outputs.parameters.promoted}}' == 'true'"

    # =========================================================================
    # APPROVAL GATE
    # =========================================================================
    - name: approval-gate
      inputs:
        parameters:
          - name: approve
            default: "NO"
            enum: ["YES", "NO"]
      outputs:
        parameters:
          - name: approve
            valueFrom:
              supplied: {}
      suspend: {}
