apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: gitops-repo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  externalSecretName: gitops-repo-es
  refreshTime: 1h
  namespaceSelectors:
    - matchLabels:
        opencloudhub.org/secret-gitops: "true"
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: gitops-repo
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repository
        data:
          url: "{{ .url }}"
          type: "{{ .type }}"
          sshPrivateKey: "{{ .sshPrivateKey }}"
    data:
      - secretKey: url
        remoteRef:
          key: platform/gitops/repos/gitops
          property: url
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
      - secretKey: type
        remoteRef:
          key: platform/gitops/repos/gitops
          property: type
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
      - secretKey: sshPrivateKey
        remoteRef:
          key: platform/gitops/repos/gitops
          property: sshPrivateKey
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: data-registry-repo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  externalSecretName: data-registry-repo-es
  namespaceSelectors:
    - matchLabels:
        opencloudhub.org/secret-gitops: "true"
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: data-registry-repo
      creationPolicy: Owner
      deletionPolicy: Retain
    data:
      - secretKey: url
        remoteRef:
          key: platform/gitops/repos/data-registry
          property: url
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
      - secretKey: type
        remoteRef:
          key: platform/gitops/repos/data-registry
          property: type
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
      - secretKey: sshPrivateKey
        remoteRef:
          key: platform/gitops/repos/data-registry
          property: sshPrivateKey
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
