apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: dockerhub-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  externalSecretName: dockerhub-secret-es
  refreshTime: 1h
  namespaceSelectors:
    - matchLabels:
        opencloudhub.org/secret-registry: "true"
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: dockerhub-secret
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "https://index.docker.io/v1/": {
                  "username": "{{ .username }}",
                  "password": "{{ .password }}",
                  "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
                }
              }
            }
    data:
      - secretKey: username
        remoteRef:
          key: platform/docker/registry
          property: username
      - secretKey: password
        remoteRef:
          key: platform/docker/registry
          property: password
