apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

helmCharts:
  - name: tempo
    releaseName: tempo
    version: 1.23.2
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    valuesInline:
      tempo:
        extraEnvFrom:
          - secretRef:
              name: minio-tenant-secret
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        storage:
          trace:
            backend: s3
            s3:
              endpoint: minio.minio-tenant.svc.cluster.local:80
              bucket: tempo-traces
              region: us-east-1
              access_key: admin
              secret_key: 12345678  # TOD : fix
              insecure: true

        reportingEnabled: false
        # ENABLE metrics generation for service graphs and TraceQL
        overrides:
          defaults:
            metrics_generator:
              processors:
                - service-graphs
                - span-metrics
                - local-blocks
        metricsGenerator:
          enabled: true
          remoteWriteUrl: "http://prometheus-server.observability.svc.cluster.local/api/v1/write"

      serviceMonitor:
        enabled: true
