apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-executor
  namespace: mlops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor
  namespace: mlops
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  - apiGroups:
      - ray.io
    resources:
      - rayjobs
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ray.io
    resources:
      - rayservices
    verbs:
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor
  namespace: mlops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-executor
subjects:
  - kind: ServiceAccount
    name: workflow-executor
    namespace: mlops
