#!/bin/bash
# Show cluster and running tests status

echo ""
echo "══════════════════════════════════════════════════"
echo "📊 CLUSTER STATUS"
echo "══════════════════════════════════════════════════"
echo ""
echo "Context: $(kubectl config current-context 2>/dev/null || echo 'Not connected')"
echo ""
echo "Nodes:"
kubectl get nodes 2>/dev/null || echo "  (not available)"
echo ""
echo "──────────────────────────────────────────────────"
echo "🧪 Running Tests"
echo "──────────────────────────────────────────────────"
kubectl get testruns -n k6-testing 2>/dev/null || echo "  None"
echo ""
echo "──────────────────────────────────────────────────"
echo "🚀 Argo Workflows"
echo "──────────────────────────────────────────────────"
kubectl get workflows -n mlops --sort-by=.metadata.creationTimestamp 2>/dev/null | tail -6 || echo "  None"
echo ""
echo "══════════════════════════════════════════════════"
echo ""
