apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-db-user-es
  namespace: mlops
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mlflow-db-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          app: mlflow-db-cluster
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: mlops/storage/cnpg/mlflow
        property: username
    - secretKey: password
      remoteRef:
        key: mlops/storage/cnpg/mlflow
        property: password

--- 
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-tenant-secret-es
  namespace: mlops
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-tenant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accesskey: "{{ .accesskey }}"
        secretkey: "{{ .secretkey }}"
  data:
    - secretKey: accesskey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: secretkey