apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability


resources:
  - external-secrets.yaml


helmCharts:
  - name: loki
    releaseName: loki
    version: 6.31.0
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    valuesInline:
      deploymentMode: SingleBinary
      singleBinary:
        replicas: 1
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        extraEnvFrom:
          - secretRef:
              name: minio-tenant-secret
      
      # Zero out replica counts of other deployment modes
      backend:
        replicas: 0
      read:
        replicas: 0
      write:
        replicas: 0
      ingester:
        replicas: 0
      querier:
        replicas: 0
      queryFrontend:
        replicas: 0
      queryScheduler:
        replicas: 0
      distributor:
        replicas: 0
      compactor:
        replicas: 0
      indexGateway:
        replicas: 0
      bloomCompactor:
        replicas: 0
      bloomGateway:
        replicas: 0
      ruler:
        replicas: 0
      
      # Loki configuration
      loki:
        auth_enabled: false
        commonConfig:
          replication_factor: 1
        schemaConfig:
          configs:
            - from: 2024-04-01
              store: tsdb
              object_store: s3
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        ingester:
          chunk_encoding: snappy
        tracing:
          enabled: true
        pattern_ingester:
          enabled: true
        limits_config:
          allow_structured_metadata: true
          volume_enabled: true
          ingestion_rate_mb: 64
          ingestion_burst_size_mb: 128
          per_stream_rate_limit: 512KB
          per_stream_rate_limit_burst: 1MB
        ruler:
          enable_api: true
        querier:
          max_concurrent: 2
        storage:
          type: s3
          bucketNames:
            chunks: loki-chunks
            ruler: loki-ruler
            admin: loki-admin
          s3:
            endpoint: minio.minio-tenant.svc.cluster.local:80
            region: us-east-1
            s3ForcePathStyle: true
            insecure: true
            accessKeyId: ${accesskey}
            secretAccessKey: ${secretkey}
        server:
          log_level: debug
        chunksCache:
          writebackSizeLimit: 10MB
