# mlops-pipeline.yaml - Main orchestration
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-pipeline
  namespace: ai-mlops
  annotations:
    workflows.argoproj.io/title: '**MLOPS Pipeline**'
    workflows.argoproj.io/description: 'End-to-end MLOps pipeline: trains, evaluates, promotes, and deploys ML models with manual/automatic approval and full lineage tracking.'
spec:
  serviceAccountName: workflow-executor

  arguments:
    parameters:
    - name: model_name
      description: "Model name (e.g., wine-classifier)"
    - name: dvc_data_version
      description: "Data version to use for training"
    - name: experiment_name
      description: "MLflow experiment name"
    - name: training_entrypoint
      value: "python src/train.py"
    - name: training_args
      value: ""
    - name: training_image
      description: "Container image with training code"
    - name: serving_image
      description: "Container image with serving code"
    - name: compute_type
      enum: [cpu-small, cpu-medium, cpu-large, gpu-small, gpu-medium, gpu-large]
      description: "Compute configuration"
    - name: approval_mode
      value: "manual"
      enum: [manual, automatic]
    - name: comparison_metric
      value: "val_acc"
    - name: comparison_higher_is_better
      value: "true"
    - name: comparison_threshold
      value: "0.05"
    - name: mlflow_tracking_uri
      value: "http://mlflow.ai.svc.cluster.local:80"

  entrypoint: main

  templates:
  - name: main
    steps:
    # Phase 1: Map compute and submit training
    - - name: map-compute
        templateRef:
          name: compute-templates
          template: map-compute-config
        arguments:
          parameters:
          - name: compute_type
            value: "{{workflow.parameters.compute_type}}"

    # Phase 2: Submit Ray training job
    - - name: submit-training
        templateRef:
          name: training-templates
          template: submit-ray-job
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: dvc_data_version
            value: "{{workflow.parameters.dvc_data_version}}"
          - name: experiment_name
            value: "{{workflow.parameters.experiment_name}}"
          - name: training_image
            value: "{{workflow.parameters.training_image}}"
          - name: training_entrypoint
            value: "{{workflow.parameters.training_entrypoint}}"
          - name: training_args
            value: "{{workflow.parameters.training_args}}"
          - name: cpu_request
            value: "{{steps.map-compute.outputs.parameters.cpu_request}}"
          - name: cpu_limit
            value: "{{steps.map-compute.outputs.parameters.cpu_limit}}"
          - name: memory_request
            value: "{{steps.map-compute.outputs.parameters.memory_request}}"
          - name: memory_limit
            value: "{{steps.map-compute.outputs.parameters.memory_limit}}"
          - name: replicas
            value: "{{steps.map-compute.outputs.parameters.replicas}}"
          - name: gpu
            value: "{{steps.map-compute.outputs.parameters.gpu}}"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"

    # Phase 3: Compare and promote to staging
    - - name: compare-promote-staging
        templateRef:
          name: mlflow-templates
          template: compare-and-promote-staging
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: metric_name
            value: "{{workflow.parameters.comparison_metric}}"
          - name: higher_is_better
            value: "{{workflow.parameters.comparison_higher_is_better}}"
          - name: threshold
            value: "{{workflow.parameters.comparison_threshold}}"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"

    # Phase 4: Running Tests
    - - name: test-staging
        templateRef:
          name: mlflow-templates
          template: test-staging-model
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: staging_version
            value: "{{steps.compare-promote-staging.outputs.parameters.staging_version}}"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"
        when: "{{steps.compare-promote-staging.outputs.parameters.promoted}} == true"

    # Phase 5: Manual approval (only if tests pass)
    - - name: approval
        template: approval-gate
        when: "{{workflow.parameters.approval_mode}} == manual && '{{steps.test-staging.outputs.parameters.test_passed}}' == 'true'"

    # Phase 6: Promote to production (only if tests passed)
    - - name: promote-production
        templateRef:
          name: mlflow-templates
          template: promote-to-production
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: staging_version
            value: "{{steps.compare-promote-staging.outputs.parameters.staging_version}}"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"
        when: "({{workflow.parameters.approval_mode}} == automatic || '{{steps.approval.outputs.parameters.approve}}' == 'YES') && '{{steps.test-staging.outputs.parameters.test_passed}}' == 'true'"

    # Phase 7: Deploy to production (atomic: GitOps + MLflow tagging)
    - - name: deploy-to-production
        templateRef:
          name: deployment-templates
          template: deploy-model
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: model_uri
            value: "models:/prod.{{workflow.parameters.model_name}}/{{steps.promote-production.outputs.parameters.prod_version}}"
          - name: serving_image
            value: "{{workflow.parameters.serving_image}}"
          - name: deployed_by
            value: "pipeline"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"

    # # Phase 7: Update Ray Serve Definition
    # - - name: update-gitops
    #     templateRef:
    #       name: deployment-templates
    #       template: update-gitops
    #     arguments:
    #       parameters:
    #       - name: model_name
    #         value: "{{workflow.parameters.model_name}}"
    #       - name: prod_version
    #         value: "{{steps.promote-production.outputs.parameters.prod_version}}"
    #       - name: serving_image
    #         value: "{{workflow.parameters.serving_image}}"

    # # Phase 8: Tag deployment info
    # - - name: tag-mlflow-prod-model
    #     templateRef:
    #       name: mlflow-templates
    #       template: tag-mlflow-prod-model
    #     arguments:
    #       parameters:
    #       - name: model_name
    #         value: "{{workflow.parameters.model_name}}"
    #       - name: prod_version
    #         value: "{{steps.promote-production.outputs.parameters.prod_version}}"
    #       - name: staging_version
    #         value: "{{steps.compare-promote-staging.outputs.parameters.staging_version}}"
    #       - name: ci_version
    #         value: "{{steps.compare-promote-staging.outputs.parameters.ci_version}}"
    #       - name: approval_mode
    #         value: "{{workflow.parameters.approval_mode}}"
    #       - name: mlflow_tracking_uri
    #         value: "{{workflow.parameters.mlflow_tracking_uri}}"


  # Approval gate template
  - name: approval-gate
    inputs:
      parameters:
        - name: approve
          default: 'NO'
          enum:
            - 'YES'
            - 'NO'
          description: >-
            Choose YES to continue workflow and deploy to production
    outputs:
      parameters:
        - name: approve
          valueFrom:
            supplied: {}
    suspend: {}
