# mlops-pipeline.yaml - Main orchestration
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-pipeline
  namespace: ai
spec:
  serviceAccountName: workflow-executor

  arguments:
    parameters:
    - name: model_name
      description: "Model name (e.g., wine-classifier)"
    - name: experiment_name
      description: "MLflow experiment name"
    - name: compute_type
      enum: [cpu-small, cpu-medium, cpu-large, gpu-small, gpu-medium, gpu-large]
      description: "Compute configuration"
    - name: approval_mode
      value: "manual"
      enum: [manual, automatic]
    - name: comparison_metric
      value: "val_acc"
    - name: higher_is_better
      value: "true"
    - name: comparison_threshold
      value: "0.05"
    - name: training_image
      description: "Container image with training and serving code"
    - name: training_entrypoint
      value: "python src/training/train.py"
    - name: training_args
      value: ""
    - name: mlflow_tracking_uri
      value: "http://mlflow.ai.svc.cluster.local:80"
    - name: ray_service_name
      value: "wine-classifier-service"
    - name: ray_service_namespace
      value: "ai"

  entrypoint: main

  templates:
  - name: main
    steps:
    # Phase 1: Map compute and submit training
    - - name: map-compute
        templateRef:
          name: compute-templates
          template: map-compute-config
        arguments:
          parameters:
          - name: compute_type
            value: "{{workflow.parameters.compute_type}}"

    # Phase 2: Submit Ray training job
    - - name: submit-training
        templateRef:
          name: training-templates
          template: submit-ray-job
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: experiment_name
            value: "{{workflow.parameters.experiment_name}}"
          - name: training_image
            value: "{{workflow.parameters.training_image}}"
          - name: training_entrypoint
            value: "{{workflow.parameters.training_entrypoint}}"
          - name: training_args
            value: "{{workflow.parameters.training_args}}"
          - name: cpu
            value: "{{steps.map-compute.outputs.parameters.cpu}}"
          - name: memory
            value: "{{steps.map-compute.outputs.parameters.memory}}"
          - name: replicas
            value: "{{steps.map-compute.outputs.parameters.replicas}}"
          - name: gpu
            value: "{{steps.map-compute.outputs.parameters.gpu}}"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"

    # Phase 3: Compare and promote to staging
    - - name: compare-promote
        templateRef:
          name: mlflow-templates
          template: compare-and-promote
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: metric
            value: "{{workflow.parameters.comparison_metric}}"
          - name: higher_is_better
            value: "{{workflow.parameters.higher_is_better}}"
          - name: threshold
            value: "{{workflow.parameters.comparison_threshold}}"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"

    # Phase 4: Manual approval
    - - name: approval
        templateRef:
          name: approval-templates
          template: approval-with-check
        arguments:
          parameters:
          - name: approval_mode
            value: "{{workflow.parameters.approval_mode}}"

    # Phase 5: Promote to production in MLflow
    - - name: promote-production
        templateRef:
          name: mlflow-templates
          template: promote-to-production
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: staging_version
            value: "{{steps.compare-promote.outputs.parameters.staging_version}}"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"
        when: "{{workflow.parameters.approval_mode}} == automatic || '{{steps.approval.outputs.parameters.approved}}' == 'true'"

    # Phase 6: Reload Ray Serve to pick up new @champion model
    - - name: reload-ray-serve
        templateRef:
          name: deployment-templates
          template: reload-ray-serve
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: prod_version
            value: "{{steps.promote-production.outputs.parameters.prod_version}}"
          - name: ray_service_name
            value: "{{workflow.parameters.ray_service_name}}"
          - name: ray_service_namespace
            value: "{{workflow.parameters.ray_service_namespace}}"
        when: "{{workflow.parameters.approval_mode}} == automatic || '{{steps.approval.outputs.parameters.approved}}' == 'true'"

    # Phase 7: Tag deployment info
    - - name: tag-deployment
        templateRef:
          name: mlflow-templates
          template: tag-deployment-ready
        arguments:
          parameters:
          - name: model_name
            value: "{{workflow.parameters.model_name}}"
          - name: prod_version
            value: "{{steps.promote-production.outputs.parameters.prod_version}}"
          - name: staging_version
            value: "{{steps.compare-promote.outputs.parameters.staging_version}}"
          - name: ci_version
            value: "{{steps.compare-promote.outputs.parameters.ci_version}}"
          - name: approval_mode
            value: "{{workflow.parameters.approval_mode}}"
          - name: mlflow_tracking_uri
            value: "{{workflow.parameters.mlflow_tracking_uri}}"
        when: "{{workflow.parameters.approval_mode}} == automatic || '{{steps.approval.outputs.parameters.approved}}' == 'true'"
