apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  gatewayClassName: istio
  listeners:
  - name: https-internal
    port: 443
    protocol: HTTPS
    hostname: "*.internal.opencloudhub.org"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: ingress-gateway-cert
        group: ''
        kind: Secret
  - name: https-external
    port: 443
    protocol: HTTPS
    hostname: "api.opencloudhub.org"  # Add external domain
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: ingress-gateway-cert  # Same cert or different one
        group: ''
        kind: Secret
