apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  gatewayClassName: istio
  listeners:
  # Internal services
  - name: https-internal
    port: 443
    protocol: HTTPS
    hostname: "*.internal.opencloudhub.org"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: ingress-gateway-cert  # TODO: differentiate later

  # External APIs
  - name: https-api
    port: 443
    protocol: HTTPS
    hostname: "api.opencloudhub.org"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: ingress-gateway-cert

  # External applications
  - name: https-app
    port: 443
    protocol: HTTPS
    hostname: "app.opencloudhub.org"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: ingress-gateway-cert
