apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  # Security policies ApplicationSet and AppProjects
  - repoURL: git@github.com:opencloudhub/gitops.git
    path: src/app-projects
    targetRevision: HEAD
  - repoURL: git@github.com:opencloudhub/gitops.git
    path: src/application-sets/security
    targetRevision: HEAD
  # Platform team apps
  - repoURL: git@github.com:opencloudhub/gitops.git
    path: src/application-sets/platform
    targetRevision: HEAD
  # Team Apps
  - repoURL: git@github.com:opencloudhub/gitops.git
    path: src/application-sets/teams
    targetRevision: HEAD

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
