# =============================================================================
# src/platform/core/external-secrets/cluster-secret-stores.yaml
# ClusterSecretStore - Vault Backend Configuration
# =============================================================================
#
# Configures the External Secrets Operator to connect to HashCorp Vault.
# This ClusterSecretStore is referenced by all ExternalSecrets and
# ClusterExternalSecrets in the cluster.
#
# Authentication:
#   Uses a Kubernetes secret (vault-token) created during bootstrap.
#   The token is stored in the external-secrets namespace.
#
# Vault Configuration:
#   - Server: host.minikube.internal:8200 (local dev Vault)
#   - Path: kv (KV v2 secrets engine)
#   - For production: Update server URL to your Vault instance
#
# =============================================================================

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: "http://host.minikube.internal:8200" # Works in minikube
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: external-secrets
