apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: platform/observability/grafana/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: platform/observability/grafana/credentials
        property: password
