apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-tenant-secret-es
  namespace: ai-serving
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-tenant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accesskey: "{{ .accesskey }}"
        secretkey: "{{ .secretkey }}"
  data:
    - secretKey: accesskey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: platform/storage/minio-tenant/credentials
        property: secretkey
