# Wine Classifier - Complete Service Definition
---
# RayService for model serving
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: fashion-mnist-classifier-service
  namespace: ai
  annotations:
    argocd-image-updater.argoproj.io/image-list: ray-head=opencloudhuborg/fashion-mnist-classifier:latest,ray-worker=opencloudhuborg/fashion-mnist-classifier:latest
    argocd-image-updater.argoproj.io/serving.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    serving-image-digest: "" # ArgoCD Image Updater will update this
  labels:
    app.kubernetes.io/name: fashion-mnist-classifier
spec:
  serviceUnhealthySecondThreshold: 900
  deploymentUnhealthySecondThreshold: 300
  serveConfigV2: |
    applications:
      - name: fashion-mnist_classifier_app
        import_path: src.serve:app_builder
        route_prefix: /models/fashion-mnist-classifier
        deployments:
          - name: FashionMNISTClassifier
            num_replicas: 1
            user_config:
              model_uri: models:/prod.fashion-mnist-classifier/1
            ray_actor_options:
              num_cpus: 1
              memory: 1073741824  # 1GB for the deployment actor
  rayClusterConfig:
    rayVersion: '2.48.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
        metrics-export-port: '8080'
        object-store-memory: '536870912'  # 512MB for object store
      template:
        metadata:
          annotations:
            serving-image-digest: "{{ .metadata.annotations.serving-image-digest }}"
        spec:
          nodeSelector:
            node.opencloudhub.org/application: "true"
          containers:
          - name: ray-head
            image: opencloudhuborg/fashion-mnist-classifier:latest
            imagePullPolicy: Always
            ports:
            - containerPort: 8000
              name: serve
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8265
              name: dashboard
              protocol: TCP
            resources:
              requests:
                cpu: "1"
                memory: "3Gi"
              limits:
                cpu: "2"
                memory: "4Gi"
            env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.ai.svc.cluster.local:80"
            - name: RAY_GRAFANA_HOST
              value: "http://grafana.observability.svc.cluster.local:80"
            - name: RAY_PROMETHEUS_HOST
              value: "http://prometheus-server.observability.svc.cluster.local:80"
            - name: RAY_GRAFANA_IFRAME_HOST
              value: "https://grafana.observability.internal.opencloudhub.org"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-tenant-secret
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-tenant-secret
                  key: secretkey
            - name: AWS_ENDPOINT_URL
              value: "https://minio-api.storage.internal.opencloudhub.org"

    workerGroupSpecs:
    - groupName: serving-workers
      replicas: 1
      minReplicas: 1
      maxReplicas: 2
      template:
        spec:
          nodeSelector:
            node.opencloudhub.org/application: "true"
          containers:
          - name: ray-worker
            image: opencloudhuborg/fashion-mnist-classifier:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"
              limits:
                cpu: "2"
                memory: "3Gi"
            env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.ai.svc.cluster.local:80"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-tenant-secret
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-tenant-secret
                  key: secretkey
            - name: AWS_ENDPOINT_URL
              value: "https://minio-api.storage.internal.opencloudhub.org"

---
# HTTPRoute for model API (external access)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fashion-mnist-classifier-api-route
  namespace: ai
  labels:
    app.kubernetes.io/name: fashion-mnist-classifier
    app.kubernetes.io/component: gateway-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress

  hostnames:
  - "api.opencloudhub.org"

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /models/fashion-mnist-classifier
    backendRefs:
    - name: fashion-mnist-classifier-service-head-svc
      port: 8000
      kind: Service
      weight: 100
      group: ""

---
# HTTPRoute for Ray Dashboard (internal only - data scientists)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fashion-mnist-classifier-dashboard-route
  namespace: ai
  labels:
    app.kubernetes.io/name: fashion-mnist-classifier
    app.kubernetes.io/component: dashboard-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress

  hostnames:
  - "fashion-mnist-classifier.ai.internal.opencloudhub.org"

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: fashion-mnist-classifier-service-head-svc  # Ray dashboard service
      port: 8265
      kind: Service
      weight: 100
      group: ""
