apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ray-templates
  namespace: mlops
  annotations:
    description: "Reusable templates for Ray job submission and monitoring"
spec:
  templates:
    # ==========================================================================
    # CREATE RAYJOB FROM CONFIGMAP TEMPLATE
    # ==========================================================================
    - name: create-rayjob-from-template
      inputs:
        parameters:
          - name: configmap_name
            description: "Name of ConfigMap containing rayjob.yaml template"
          - name: configmap_key
            default: "rayjob.yaml"
            description: "Key in ConfigMap containing the template"
          - name: run_label
            description: "Unique label for this run (used to find the job)"
          - name: substitutions
            description: "JSON object of KEY=VALUE substitutions, e.g. {\"IMAGE\":\"myimg\",\"REPLICAS\":\"2\"}"
      outputs:
        parameters:
          - name: job_name
            valueFrom:
              path: /tmp/job-name.txt
          - name: cluster_name
            valueFrom:
              path: /tmp/cluster-name.txt
      script:
        image: alpine/k8s:1.30.4
        command: [sh]
        source: |
          set -e

          CONFIGMAP="{{inputs.parameters.configmap_name}}"
          CONFIGMAP_KEY="{{inputs.parameters.configmap_key}}"
          RUN_LABEL="{{inputs.parameters.run_label}}"
          SUBS='{{inputs.parameters.substitutions}}'

          echo "=========================================="
          echo "CREATE RAYJOB FROM TEMPLATE"
          echo "  ConfigMap:  $CONFIGMAP"
          echo "  Key:        $CONFIGMAP_KEY"
          echo "  Run Label:  $RUN_LABEL"
          echo "=========================================="

          # Check ConfigMap exists
          if ! kubectl get configmap -n mlops "$CONFIGMAP" > /dev/null 2>&1; then
            echo "ERROR: ConfigMap '$CONFIGMAP' not found in namespace mlops"
            kubectl get configmap -n mlops
            exit 1
          fi

          # Extract template from ConfigMap - escape dots in key name for jsonpath
          ESCAPED_KEY=$(echo "$CONFIGMAP_KEY" | sed 's/\./\\./g')
          kubectl get configmap -n mlops "$CONFIGMAP" -o jsonpath="{.data.${ESCAPED_KEY}}" > /tmp/template.yaml

          if [ ! -s /tmp/template.yaml ]; then
            echo "ERROR: Template is empty or key '$CONFIGMAP_KEY' not found"
            kubectl get configmap -n mlops "$CONFIGMAP" -o yaml
            exit 1
          fi

          echo "Template extracted successfully"

          # Apply substitutions using jq to parse JSON and sed to replace
          # This handles each substitution safely
          cp /tmp/template.yaml /tmp/rayjob.yaml

          echo "$SUBS" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
            # Trim whitespace from value
            value=$(echo "$value" | xargs)
            # Escape & for sed (& means matched pattern in sed replacement)
            escaped_value=$(printf '%s' "$value" | sed 's/&/\\&/g')
            echo "  Substituting: \${$key} -> $value"
            sed -i "s|\${${key}}|${escaped_value}|g" /tmp/rayjob.yaml
          done

          # Also substitute RUN_LABEL
          sed -i "s|\${RUN_LABEL}|${RUN_LABEL}|g" /tmp/rayjob.yaml

          echo ""
          echo "Generated YAML:"
          echo "----------------------------------------"
          cat /tmp/rayjob.yaml
          echo "----------------------------------------"
          echo ""

          # Validate YAML syntax (use create for generateName)
          if ! kubectl create --dry-run=client -f /tmp/rayjob.yaml > /dev/null 2>&1; then
            echo "ERROR: Generated YAML is invalid"
            kubectl create --dry-run=client -f /tmp/rayjob.yaml
            exit 1
          fi

          echo "YAML validation passed"

          # Create the RayJob
          if ! kubectl create -f /tmp/rayjob.yaml; then
            echo "ERROR: Failed to create RayJob"
            exit 1
          fi

          echo "RayJob created, waiting for it to appear..."
          sleep 3

          # Find the job by label
          JOB_NAME=$(kubectl get rayjobs -n mlops -l run="$RUN_LABEL" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

          if [ -z "$JOB_NAME" ]; then
            echo "ERROR: Could not find RayJob with label run=$RUN_LABEL"
            kubectl get rayjobs -n mlops
            exit 1
          fi

          echo "RayJob created: $JOB_NAME"
          echo "$JOB_NAME" > /tmp/job-name.txt

          # Wait for cluster name to be assigned
          for i in $(seq 1 30); do
            CLUSTER_NAME=$(kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.rayClusterName}' 2>/dev/null)
            if [ -n "$CLUSTER_NAME" ]; then
              break
            fi
            sleep 2
          done

          if [ -z "$CLUSTER_NAME" ]; then
            CLUSTER_NAME="unknown"
          fi

          echo "$CLUSTER_NAME" > /tmp/cluster-name.txt
          echo "Ray cluster: $CLUSTER_NAME"

          echo ""
          echo "=========================================="
          echo "SUCCESS: RayJob created"
          echo "  Job:     $JOB_NAME"
          echo "  Cluster: $CLUSTER_NAME"
          echo "=========================================="

    # ==========================================================================
    # WAIT FOR RAYJOB COMPLETION - SIMPLE KUBECTL ONLY
    # ==========================================================================
    - name: wait-for-rayjob
      inputs:
        parameters:
          - name: job_name
          - name: timeout_seconds
            default: "3600"
      outputs:
        parameters:
          - name: job_status
            valueFrom:
              path: /tmp/job-status.txt
      script:
        image: bitnami/kubectl:latest
        command: [bash]
        source: |
          set -e

          JOB_NAME="{{inputs.parameters.job_name}}"
          TIMEOUT="{{inputs.parameters.timeout_seconds}}"

          echo "PENDING" > /tmp/job-status.txt

          echo "Monitoring RayJob: $JOB_NAME"

          ELAPSED=0
          HEAD_POD=""

          while [ $ELAPSED -lt $TIMEOUT ]; do
            # Get current status
            DEPLOY=$(kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.jobDeploymentStatus}' 2>/dev/null || echo "")
            JOB=$(kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.jobStatus}' 2>/dev/null || echo "")

            # Check for pod creation failure
            FAIL_MSG=$(kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.conditions[?(@.reason=="FailedCreateHeadPod")].message}' 2>/dev/null || echo "")
            if [ -n "$FAIL_MSG" ]; then
              echo ""
              echo "ERROR: $FAIL_MSG"
              echo "FAILED" > /tmp/job-status.txt
              exit 1
            fi

            # Check job status
            case "$JOB" in
              SUCCEEDED)
                echo ""
                echo "SUCCESS"
                echo "SUCCEEDED" > /tmp/job-status.txt
                exit 0
                ;;
              FAILED|STOPPED)
                echo ""
                echo "FAILED: $JOB"
                kubectl logs -n mlops -l ray.io/cluster=$(kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.rayClusterName}'),ray.io/node-type=head --tail=50 2>/dev/null || true
                echo "FAILED" > /tmp/job-status.txt
                exit 1
                ;;
            esac

            # Check deployment status
            if [ "$DEPLOY" = "Failed" ]; then
              echo "Deployment failed"
              echo "FAILED" > /tmp/job-status.txt
              exit 1
            fi

            # Try to find and stream logs from head pod once cluster is running
            if [ "$DEPLOY" = "Running" ] && [ -z "$HEAD_POD" ]; then
              CLUSTER=$(kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.rayClusterName}' 2>/dev/null || echo "")
              if [ -n "$CLUSTER" ]; then
                HEAD_POD=$(kubectl get pods -n mlops -l "ray.io/cluster=$CLUSTER,ray.io/node-type=head" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")
                if [ -n "$HEAD_POD" ]; then
                  echo "Streaming logs from: $HEAD_POD"
                  kubectl logs -n mlops "$HEAD_POD" -f 2>/dev/null &
                fi
              fi
            fi

            echo "[$ELAPSED s] deploy=$DEPLOY job=$JOB"
            sleep 10
            ELAPSED=$((ELAPSED + 10))
          done

          echo "TIMEOUT"
          echo "TIMEOUT" > /tmp/job-status.txt
          exit 1
