apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ray-templates
  namespace: mlops
  annotations:
    description: "Reusable templates for Ray job submission and monitoring"
spec:
  templates:
    # ==========================================================================
    # CREATE RAYJOB FROM CONFIGMAP TEMPLATE
    # ==========================================================================
    - name: create-rayjob-from-template
      inputs:
        parameters:
          - name: configmap_name
            description: "Name of ConfigMap containing rayjob.yaml template"
          - name: configmap_key
            default: "rayjob.yaml"
            description: "Key in ConfigMap containing the template"
          - name: run_label
            description: "Unique label for this run (used to find the job)"
          - name: substitutions
            description: "JSON object of KEY=VALUE substitutions, e.g. {\"IMAGE\":\"myimg\",\"REPLICAS\":\"2\"}"
      outputs:
        parameters:
          - name: job_name
            valueFrom:
              path: /tmp/job-name.txt
          - name: cluster_name
            valueFrom:
              path: /tmp/cluster-name.txt
      script:
        image: alpine/k8s:1.30.4
        command: [sh]
        source: |
          set -e

          CONFIGMAP="{{inputs.parameters.configmap_name}}"
          CONFIGMAP_KEY="{{inputs.parameters.configmap_key}}"
          RUN_LABEL="{{inputs.parameters.run_label}}"
          SUBS='{{inputs.parameters.substitutions}}'

          echo "=========================================="
          echo "CREATE RAYJOB FROM TEMPLATE"
          echo "  ConfigMap:  $CONFIGMAP"
          echo "  Key:        $CONFIGMAP_KEY"
          echo "  Run Label:  $RUN_LABEL"
          echo "=========================================="

          # Check ConfigMap exists
          if ! kubectl get configmap -n mlops "$CONFIGMAP" > /dev/null 2>&1; then
            echo "ERROR: ConfigMap '$CONFIGMAP' not found in namespace mlops"
            kubectl get configmap -n mlops
            exit 1
          fi

          # Extract template from ConfigMap - escape dots in key name for jsonpath
          ESCAPED_KEY=$(echo "$CONFIGMAP_KEY" | sed 's/\./\\./g')
          kubectl get configmap -n mlops "$CONFIGMAP" -o jsonpath="{.data.${ESCAPED_KEY}}" > /tmp/template.yaml

          if [ ! -s /tmp/template.yaml ]; then
            echo "ERROR: Template is empty or key '$CONFIGMAP_KEY' not found"
            kubectl get configmap -n mlops "$CONFIGMAP" -o yaml
            exit 1
          fi

          echo "Template extracted successfully"

          # Apply substitutions using jq to parse JSON and sed to replace
          # This handles each substitution safely
          cp /tmp/template.yaml /tmp/rayjob.yaml

          echo "$SUBS" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
            # Trim whitespace from value
            value=$(echo "$value" | xargs)
            # Escape & for sed (& means matched pattern in sed replacement)
            escaped_value=$(printf '%s' "$value" | sed 's/&/\\&/g')
            echo "  Substituting: \${$key} -> $value"
            sed -i "s|\${${key}}|${escaped_value}|g" /tmp/rayjob.yaml
          done

          # Also substitute RUN_LABEL
          sed -i "s|\${RUN_LABEL}|${RUN_LABEL}|g" /tmp/rayjob.yaml

          echo ""
          echo "Generated YAML:"
          echo "----------------------------------------"
          cat /tmp/rayjob.yaml
          echo "----------------------------------------"
          echo ""

          # Validate YAML syntax (use create for generateName)
          if ! kubectl create --dry-run=client -f /tmp/rayjob.yaml > /dev/null 2>&1; then
            echo "ERROR: Generated YAML is invalid"
            kubectl create --dry-run=client -f /tmp/rayjob.yaml
            exit 1
          fi

          echo "YAML validation passed"

          # Create the RayJob
          if ! kubectl create -f /tmp/rayjob.yaml; then
            echo "ERROR: Failed to create RayJob"
            exit 1
          fi

          echo "RayJob created, waiting for it to appear..."
          sleep 3

          # Find the job by label
          JOB_NAME=$(kubectl get rayjobs -n mlops -l run="$RUN_LABEL" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

          if [ -z "$JOB_NAME" ]; then
            echo "ERROR: Could not find RayJob with label run=$RUN_LABEL"
            kubectl get rayjobs -n mlops
            exit 1
          fi

          echo "RayJob created: $JOB_NAME"
          echo "$JOB_NAME" > /tmp/job-name.txt

          # Wait for cluster name to be assigned
          for i in $(seq 1 30); do
            CLUSTER_NAME=$(kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.rayClusterName}' 2>/dev/null)
            if [ -n "$CLUSTER_NAME" ]; then
              break
            fi
            sleep 2
          done

          if [ -z "$CLUSTER_NAME" ]; then
            CLUSTER_NAME="unknown"
          fi

          echo "$CLUSTER_NAME" > /tmp/cluster-name.txt
          echo "Ray cluster: $CLUSTER_NAME"

          echo ""
          echo "=========================================="
          echo "SUCCESS: RayJob created"
          echo "  Job:     $JOB_NAME"
          echo "  Cluster: $CLUSTER_NAME"
          echo "=========================================="

    # ==========================================================================
    # WAIT FOR RAYJOB COMPLETION - USES RAY CLI
    # ==========================================================================
    - name: wait-for-rayjob
  inputs:
    parameters:
      - name: job_name
      - name: timeout_seconds
        default: "3600"
  outputs:
    parameters:
      - name: job_status
        valueFrom:
          path: /tmp/job-status.txt
  script:
    image: rayproject/ray:2.48.0-py312
    command: [bash]
    source: |
      set -e

      JOB_NAME="{{inputs.parameters.job_name}}"
      TIMEOUT="{{inputs.parameters.timeout_seconds}}"

      echo "PENDING" > /tmp/job-status.txt

      # Install kubectl
      wget -q "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl" -O /tmp/kubectl
      chmod +x /tmp/kubectl

      echo "Waiting for RayJob $JOB_NAME to be ready..."

      # Wait for job ID and cluster name to be available
      ELAPSED=0
      RAY_JOB_ID=""
      CLUSTER_NAME=""
      while [ -z "$RAY_JOB_ID" ] && [ $ELAPSED -lt 300 ]; do
        RAY_JOB_ID=$(/tmp/kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.jobId}' 2>/dev/null || echo "")
        CLUSTER_NAME=$(/tmp/kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.rayClusterName}' 2>/dev/null || echo "")
        
        if [ -z "$RAY_JOB_ID" ]; then
          # Check for early failures
          FAIL=$(/tmp/kubectl get rayjob -n mlops "$JOB_NAME" -o jsonpath='{.status.jobDeploymentStatus}' 2>/dev/null || echo "")
          if [ "$FAIL" = "Failed" ]; then
            echo "RayJob deployment failed"
            /tmp/kubectl describe rayjob -n mlops "$JOB_NAME"
            echo "FAILED" > /tmp/job-status.txt
            exit 1
          fi
          sleep 5
          ELAPSED=$((ELAPSED + 5))
        fi
      done

      if [ -z "$RAY_JOB_ID" ]; then
        echo "Timeout waiting for Ray job ID"
        echo "FAILED" > /tmp/job-status.txt
        exit 1
      fi

      # Use cluster name for the head service (not job name)
      RAY_ADDRESS="http://${CLUSTER_NAME}-head-svc.mlops.svc.cluster.local:8265"

      echo "=========================================="
      echo "Ray Job ID: $RAY_JOB_ID"
      echo "Ray Cluster: $CLUSTER_NAME"
      echo "Ray Address: $RAY_ADDRESS"
      echo "=========================================="
      echo ""

      # Wait for head service to be reachable
      echo "Waiting for Ray head service..."
      for i in $(seq 1 60); do
        if ray job status "$RAY_JOB_ID" --address "$RAY_ADDRESS" > /dev/null 2>&1; then
          echo "Ray head service is ready"
          break
        fi
        sleep 5
      done

      # Stream logs and wait for completion
      if timeout $TIMEOUT ray job logs -f "$RAY_JOB_ID" --address "$RAY_ADDRESS"; then
        echo ""
        echo "=========================================="
        echo "SUCCESS"
        echo "=========================================="
        echo "SUCCEEDED" > /tmp/job-status.txt
        exit 0
      else
        EXIT_CODE=$?
        echo ""
        echo "=========================================="
        echo "FAILED (exit code: $EXIT_CODE)"
        echo "=========================================="
        ray job status "$RAY_JOB_ID" --address "$RAY_ADDRESS" || true
        echo "FAILED" > /tmp/job-status.txt
        exit 1
      fi