apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: rag-evaluation-pipeline
  namespace: mlops
  annotations:
    workflows.argoproj.io/description: "Evaluate RAG prompt versions and reload endpoint with best"
spec:
  serviceAccountName: workflow-executor

  arguments:
    parameters:
      - name: image
        description: "Docker image for evaluation"
      - name: prompt_versions
        description: "Comma-separated prompt versions to evaluate (e.g., 1,2,3)"
        default: "1,2,3"
      - name: dvc_data_version
        description: "DVC data version for evaluation dataset"
        default: "opencloudhub-readmes-rag-evaluation-v1.0.0"
      - name: auto_promote
        description: "Auto-promote best prompt to @champion"
        default: "true"
      - name: prompt_name
        description: "MLflow prompt name"
        default: "readme-rag-prompt"

  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: run-evaluation
            template: evaluate-prompts

        - - name: reload-rag-endpoint
            template: reload-endpoint
            when: "{{workflow.parameters.auto_promote}} == true"

    # ==========================================================================
    # EVALUATE PROMPTS
    # ==========================================================================
    - name: evaluate-prompts
      container:
        image: "{{workflow.parameters.image}}"
        command: [python, -m, src.prompts.evaluate_prompts]
        args:
          - --prompt-name
          - "{{workflow.parameters.prompt_name}}"
          - --prompt-versions
          - "{{workflow.parameters.prompt_versions}}"
          - --dvc-data-version
          - "{{workflow.parameters.dvc_data_version}}"
          - --auto-promote
        envFrom:
          - configMapRef:
              name: models-job-env
          - configMapRef:
              name: rag-evaluation-env
          - secretRef:
              name: models-job-secrets
          - secretRef:
              name: demo-app-db-user
        env:
          - name: DOCKER_IMAGE_TAG
            value: "{{workflow.parameters.image}}"
          - name: ARGO_WORKFLOW_UID
            value: "{{workflow.uid}}"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

    # ==========================================================================
    # RELOAD RAG ENDPOINT
    # ==========================================================================
    - name: reload-endpoint
      container:
        image: curlimages/curl:8.5.0
        command: [sh, -c]
        args:
          - |
            echo "Reloading RAG endpoint with @champion prompt..."
            curl -X POST \
              http://demo-app-genai-backend.demo-app.svc.cluster.local:8000/admin/reload-prompt \
              -H "Content-Type: application/json" \
              -d '{"prompt_version": null}' \
              --fail --silent --show-error
            echo ""
            echo "✓ RAG endpoint reloaded with champion prompt"
